name: Release
on:
  push:
    branches:
      - CrowdSale

  # manual trigger
  workflow_dispatch:

jobs:
  curl:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA_SHORT: ${GITHUB_SHA::8}
    steps:
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # extract branch name on pull request
      - name: Print branch name
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST -F token=${{ secrets.GITLAB_CI_TOKEN }} -F ref=master -F variables[_repo_ref]= ${{ env.GITHUB_REF_NAME }} -F variables[_img_tag]= ${{ env.GITHUB_SHA_SHORT }} https://gitlab.com/api/v4/projects/22406878/trigger/pipeline
