name: Release
on:
  push:
    branches:
      - CrowdSale

  # manual trigger
  workflow_dispatch:

jobs:
  curl:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.0
      - name: Print environment variables
        run: |
          echo "GITHUB_REPOSITORY_SLUG=$GITHUB_REPOSITORY_SLUG"
          echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY_OWNER_SLUG=$GITHUB_REPOSITORY_OWNER_SLUG"
          echo "GITHUB_REPOSITORY_NAME=$GITHUB_REPOSITORY_NAME"
          echo "GITHUB_REPOSITORY_NAME_SLUG=$GITHUB_REPOSITORY_NAME_SLUG"
          echo "GITHUB_REF_SLUG=$GITHUB_REF_SLUG"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_REF_NAME_SLUG=$GITHUB_REF_NAME_SLUG"
          echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT"
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST \
     -F token=${{ secrets.GITLAB_CI_TOKEN }} \
     -F ref=master \
     -F variables[_repo_ref]= ${{ env.GITHUB_REF_NAME }} \
     -F variables[_img_tag]= ${{ env.GITHUB_SHA_SHORT }} \
     https://gitlab.com/api/v4/projects/22406878/trigger/pipeline
