name: Release
on:
  push:
    branches:
      - CrowdSale

  # manual trigger
  workflow_dispatch:
env:
  SHORTSHA: $(git rev-parse --short=4 ${{ github.sha }})


jobs:
  curl:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST -F token=${{ secrets.GITLAB_CI_TOKEN }} -F ref=master -F variables[_repo_ref]=${{ github.ref }} -F variables[_img_tag]=${{env.SHORTSHA}} https://gitlab.com/api/v4/projects/22406878/trigger/pipeline
